name: Update Homebrew Formula

on:
  release:
    types: [published, created, released]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to update formula for'
        required: true
        default: 'v0.0.6'

permissions:
  contents: read

jobs:
  update-homebrew:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest

    steps:
    - name: Set release tag
      id: release_tag
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
        else
          echo "tag=${{ github.event.inputs.release_tag }}" >> $GITHUB_OUTPUT
        fi

    - name: Download checksums
      run: |
        wget -q https://github.com/tgigli/sshuttle-selector-go/releases/download/${{ steps.release_tag.outputs.tag }}/checksums.txt
        cat checksums.txt

    - name: Extract checksums
      id: checksums
      run: |
        echo "darwin_amd64=$(grep 'sshuttle-selector-darwin-amd64.tar.gz' checksums.txt | cut -d' ' -f1)" >> $GITHUB_OUTPUT
        echo "darwin_arm64=$(grep 'sshuttle-selector-darwin-arm64.tar.gz' checksums.txt | cut -d' ' -f1)" >> $GITHUB_OUTPUT
        echo "linux_amd64=$(grep 'sshuttle-selector-linux-amd64.tar.gz' checksums.txt | cut -d' ' -f1)" >> $GITHUB_OUTPUT
        echo "linux_arm64=$(grep 'sshuttle-selector-linux-arm64.tar.gz' checksums.txt | cut -d' ' -f1)" >> $GITHUB_OUTPUT

    - name: Clone homebrew tap
      run: |
        git clone https://${{ secrets.HOMEBREW_TAP_TOKEN }}@github.com/tgigli/homebrew-sshuttle-selector.git homebrew-tap

    - name: Update formula
      run: |
        cd homebrew-tap

        # Update URLs to new release
        sed -i "s|download/v[0-9]\+\.[0-9]\+\.[0-9]\+/|download/${{ steps.release_tag.outputs.tag }}/|g" Formula/sshuttle-selector.rb

        # Update checksums
        sed -i "/darwin-amd64\.tar\.gz/,/sha256/ s/sha256 \"[^\"]*\"/sha256 \"${{ steps.checksums.outputs.darwin_amd64 }}\"/" Formula/sshuttle-selector.rb
        sed -i "/darwin-arm64\.tar\.gz/,/sha256/ s/sha256 \"[^\"]*\"/sha256 \"${{ steps.checksums.outputs.darwin_arm64 }}\"/" Formula/sshuttle-selector.rb
        sed -i "/linux-amd64\.tar\.gz/,/sha256/ s/sha256 \"[^\"]*\"/sha256 \"${{ steps.checksums.outputs.linux_amd64 }}\"/" Formula/sshuttle-selector.rb
        sed -i "/linux-arm64\.tar\.gz/,/sha256/ s/sha256 \"[^\"]*\"/sha256 \"${{ steps.checksums.outputs.linux_arm64 }}\"/" Formula/sshuttle-selector.rb

        # Show changes
        git diff Formula/sshuttle-selector.rb

    - name: Commit and push changes
      run: |
        cd homebrew-tap
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add Formula/sshuttle-selector.rb
        git commit -m "Update formula to ${{ steps.release_tag.outputs.tag }}

        - Update URLs to point to new release
        - Update checksums for all platforms

        🤖 Generated with [Claude Code](https://claude.ai/code)

        Co-Authored-By: Claude <noreply@anthropic.com>"

        git push origin main

    - name: Verify update
      run: |
        echo "✅ Homebrew formula updated to ${{ steps.release_tag.outputs.tag }}"
        echo "Users can now run: brew upgrade sshuttle-selector"